"""Authoritative DocForge project identity and neutral path defaults."""

MANIFEST_FILENAME = "docforge.yaml"
PROJECT_SCHEMA = "docforge.project.v1"
DEFAULT_SOURCE_PATH = "document.md"

DEFAULT_OUTPUT_DIRECTORY = "build"
DEFAULT_DOCX_FILENAME = "document.docx"
DEFAULT_DOCX_PATH = f"{DEFAULT_OUTPUT_DIRECTORY}/{DEFAULT_DOCX_FILENAME}"

DEFAULT_REVIEW_DIRECTORY = "review"
DEFAULT_REVIEW_MARKDOWN_FILENAME = "document.review.md"
DEFAULT_REVIEW_MAP_FILENAME = "document.review-map.json"
DEFAULT_REVIEW_MARKDOWN_PATH = (
    f"{DEFAULT_REVIEW_DIRECTORY}/{DEFAULT_REVIEW_MARKDOWN_FILENAME}"
)
DEFAULT_REVIEW_MAP_PATH = f"{DEFAULT_REVIEW_DIRECTORY}/{DEFAULT_REVIEW_MAP_FILENAME}"


__all__ = [
    "DEFAULT_DOCX_FILENAME",
    "DEFAULT_DOCX_PATH",
    "DEFAULT_OUTPUT_DIRECTORY",
    "DEFAULT_REVIEW_DIRECTORY",
    "DEFAULT_REVIEW_MAP_FILENAME",
    "DEFAULT_REVIEW_MAP_PATH",
    "DEFAULT_REVIEW_MARKDOWN_FILENAME",
    "DEFAULT_REVIEW_MARKDOWN_PATH",
    "DEFAULT_SOURCE_PATH",
    "MANIFEST_FILENAME",
    "PROJECT_SCHEMA",
]
